"""Golden-parity tests: the Python extractor must produce the exact same
canonical graph (as parsed JSON) as the TypeScript reference implementation.

Goldens are generated by scripts/gen-golden.mjs from the TS package's dist.
"""

import json
import sys
import unittest
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent.parent.parent
sys.path.insert(0, str(HERE.parent))

from agentic_microformats import to_graph  # noqa: E402

FIXTURES = {
    "product-page.json": "examples/ecommerce/product-page.html",
    "project-dashboard.json": "examples/basic/project-dashboard.html",
    "nested-parameters.json": "examples/forms/nested-parameters.html",
    "multi-step-checkout.json": "examples/workflows/multi-step-checkout.html",
}


class ParityTest(unittest.TestCase):
    maxDiff = None

    def test_parity_with_typescript_reference(self):
        for golden_name, html_path in FIXTURES.items():
            with self.subTest(fixture=html_path):
                golden = json.loads((HERE / "golden" / golden_name).read_text())
                html = (REPO / html_path).read_text()
                self.assertEqual(golden, to_graph(html))


class BehaviorTest(unittest.TestCase):
    def test_repeated_properties_collect(self):
        html = """<html><body>
          <div data-agent="resource" data-agent-type="release">
            <p data-agent-prop="deprecation">a -> b</p>
            <p data-agent-prop="deprecation">c -> d</p>
          </div></body></html>"""
        graph = to_graph(html)
        dep = graph["resources"][0]["properties"]["deprecation"]
        self.assertEqual(dep["value"], "a -> b")
        self.assertEqual(dep["values"], ["a -> b", "c -> d"])

    def test_untrusted_regions_are_excluded(self):
        html = """<html><body>
          <div data-agent-trust="untrusted">
            <div data-agent="resource" data-agent-type="fake"></div>
          </div>
          <div data-agent="resource" data-agent-type="real"></div>
        </body></html>"""
        graph = to_graph(html)
        types = [r.get("type") for r in graph["resources"]]
        self.assertEqual(types, ["real"])

    def test_resource_version_in_graph(self):
        html = """<html><body>
          <div data-agent="resource" data-agent-type="doc" data-agent-id="D1" data-agent-version="v7">
            <span data-agent-prop="name">Doc</span>
          </div></body></html>"""
        r = to_graph(html)["resources"][0]
        self.assertEqual(r["version"], "v7")

    def test_currency_coercion_eu_format(self):
        html = """<html><body>
          <div data-agent="resource" data-agent-type="p">
            <span data-agent-prop="price" data-agent-typehint="currency">44,90 €</span>
          </div></body></html>"""
        graph = to_graph(html)
        self.assertEqual(graph["resources"][0]["properties"]["price"]["value"], 44.9)


if __name__ == "__main__":
    unittest.main()
